In [2]:
!pip install cmake dlib face_recognition numpy

  Using cached face_recognition-1.3.0-py2.py3-none-any.whl (15 kB)
     -------------------------------------- 96.6/96.6 kB 792.2 kB/s eta 0:00:00
     ---------------------------------------- 2.5/2.5 MB 895.1 kB/s eta 0:00:00
  Using cached face_recognition_models-0.3.0.tar.gz (100.1 MB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
  Created wheel for face-recognition-models: filename=face_recognition_models-0.3.0-py2.py3-none-any.whl size=100566170 sha256=de4bde252bcbd29abf9340c92177264a774dc1a210abeda1667ce190257654fd
  Stored in directory: c:\users\el-shenawy\appdata\local\pip\cache\wheels\65\cf\0a\4f8e7e42906ede15f4cdf00d6a8f451e4785679155ce17368c
Successfully built face-recognition-models


In [2]:
import cv2
import numpy as np
import face_recognition
import os
from datetime import datetime

In [3]:
pwd

'C:\\Users\\El-Shenawy'

In [4]:
os.chdir (r"C:\Users\El-Shenawy\Attendance system\face-recognition-arabic")

In [5]:
pwd

'C:\\Users\\El-Shenawy\\Attendance system\\face-recognition-arabic'

In [6]:
path = 'images'
images = []
classNames = []
myList = os.listdir(path)
print(myList)

['elshenawy.jpg', 'mekki.jpg', 'messi.jpg', 'neymar.jpg', 'ronaldo.jpg', 'salah.jpg']


In [7]:
for cl in myList:
    curImg = cv2.imread(f'{path}/{cl}')
    images.append(curImg)
    classNames.append(os.path.splitext(cl)[0])
print(classNames)

['elshenawy', 'mekki', 'messi', 'neymar', 'ronaldo', 'salah']


In [8]:
def findEncodings(images):
    encodeList = []
    for img in images:
        img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
        encode = face_recognition.face_encodings(img)[0]
        encodeList.append(encode)
    return encodeList

In [9]:
def markAttendance(name):
    with open('Attendance.csv','r+') as f:
        myDataList = f.readlines()
        nameList = []
        for line in myDataList:
            entry = line.split(',')
            nameList.append(entry[0])
        if name not in nameList:
            now = datetime.now()
            dtString = now.strftime('%H:%M:%S')
            f.writelines(f'\n{name},{dtString}')
        

encodeListKnown = findEncodings(images)
print('Encoding Complete')

Encoding Complete


In [ ]:
cap = cv2.VideoCapture(0)
frame_resizing = 0.25

while True:
    success, img = cap.read()
    imgS = cv2.resize(img, (0, 0), fx=frame_resizing, fy=frame_resizing)
    imgS = cv2.cvtColor(imgS, cv2.COLOR_BGR2RGB)
 
    facesCurFrame = face_recognition.face_locations(imgS)
    encodesCurFrame = face_recognition.face_encodings(imgS,facesCurFrame)
 
    for encodeFace,faceLoc in zip(encodesCurFrame,facesCurFrame):
        matches = face_recognition.compare_faces(encodeListKnown,encodeFace)
        print('matches',matches)
        faceDis = face_recognition.face_distance(encodeListKnown,encodeFace)
        print(faceDis)
        matchIndex = np.argmin(faceDis)
        if matches[matchIndex]:
            name = classNames[matchIndex].upper()
            print(name)
            
            faceLoc = np.array(faceLoc)
            faceLoc = faceLoc / 0.25
            faceLoc=faceLoc.astype(int)
            
            
            y1, x2, y2, x1 = faceLoc[0], faceLoc[1], faceLoc[2], faceLoc[3]
         
            cv2.rectangle(img,(x1,y1),(x2,y2),(0,255,0),2)
            cv2.rectangle(img,(x1,y2-35),(x2,y2),(0,255,0),cv2.FILLED)
            cv2.putText(img,name,(x1+6,y2-6),cv2.FONT_HERSHEY_COMPLEX,1,(255,255,255),2)
            markAttendance(name)
 
    cv2.imshow('Webcam',img)
    key = cv2.waitKey(1)
    if key == 27:
        break
cap.release()
cv2.destroyAllWindows()


matches [True, False, False, False, False, True]
[0.55643812 0.74204932 0.83204802 0.74129355 0.69299731 0.56600301]
ELSHENAWY
matches [True, False, False, False, False, False]
[0.44498072 0.72404311 0.85349696 0.70903012 0.6924041  0.60655103]
ELSHENAWY
matches [True, False, False, False, False, True]
[0.43609836 0.7463801  0.84248836 0.72985052 0.65344635 0.59253679]
ELSHENAWY
matches [True, False, False, False, False, False]
[0.44967393 0.73850236 0.84970255 0.72491218 0.6958242  0.60376322]
ELSHENAWY
matches [True, False, False, False, False, True]
[0.44299153 0.74438798 0.87409616 0.72359406 0.67995878 0.58463677]
ELSHENAWY
matches [True, False, False, False, False, True]
[0.41689187 0.72817294 0.8363692  0.71647772 0.68897269 0.59180755]
ELSHENAWY
matches [True, False, False, False, False, True]
[0.41513081 0.74068164 0.84099275 0.73534343 0.66611988 0.58375176]
ELSHENAWY
matches [True, False, False, False, False, False]
[0.42171008 0.72823989 0.8289858  0.73457778 0.67539308 0.6